### ISSUE TITLE
Github pages hoisting is broken

### ISSUE THREAD

**Issue by pranavks** [purecatamphetamine/country-flag-icons#3]
https://purecatamphetamine.github.io/country-flag-icons/3x2/IN.svg

Unable to view the images in the hosted github pages links

**Comment by catamphetamine** [comment]
The flag URL does open in my case, so maybe it's your internet provider blocking something, or maybe it's GitHub CDN issue of some sort, though not likely.

**Comment by pranavks** [comment]
Yes, blocked by our provider, working with other networks.

For the moment we have replaced this github url with the gitlab url : https://catamphetamine.gitlab.io/country-flag-icons/3x2/IN.svg

Will this gitlab url be always available? @catamphetamine

**Comment by catamphetamine** [comment]
@pranavks 

> Will this gitlab url be always available?

I don't know if GitHub or GitLab guarantee any availability. I guess they don't because it's free hosting.
